In [13]:
#numpy==> numerical python ==> open source library==> for scientific calculation
#list ==> mutable,computation power easy
#difference between list vs numpy?
#(1) memory usage ==> list(high),numpy(low)
#(2) time consuming==> list(high),numpy(low)
#numpy==> array format

In [5]:
import numpy as np 
a= [1,2,3] 
b = np.array(a) 
b

array([1, 2, 3])

In [20]:
a=[]
size=int(input("Enter the number:"))
for i in range(size):
    val=int(input())
    a.append(val)
b=np.array(a)
b


Enter the number: 3
 1
 2
 3


array([1, 2, 3])

In [25]:
a=[1,2,3]
b=np.array(a)
b
print("total dimension:", b.ndim)#no. of dimensions
print("total shape:", b.shape)# no. of rows and no.columns
print("total elements", b.size)#no.of rows * no. of columns

total dimension: 1
total shape: (3,)
total elements 3


In [26]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
b
print("total dimension:", b.ndim)
print("total shape:", b.shape)
print("total elements", b.size)

total dimension: 2
total shape: (3, 3)
total elements 9


In [28]:
#(1)zeros()==>  it will create all values into 0
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [32]:
a=np.zeros((3,4))
print(a)
print("total dimension:", a.ndim)
print("total shape:", a.shape)
print("total elements", a.size)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
total dimension: 2
total shape: (3, 4)
total elements 12


In [33]:
#(2). ones=> it will create an array in whichall elements are one.
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [35]:
a=np.ones((3,4))
print(a)
print("total dimension:", a.ndim)
print("total shape:", a.shape)
print("total elements", a.size)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
total dimension: 2
total shape: (3, 4)
total elements 12


In [38]:
#(3). eye()==> diagonal position elements=1 ,rest all are 0.
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [6]:
a=np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
#(4). diag()==> diagonal position==>custom array,rest all are 0
a= [1,2,3] 
b = np.diag(a)
b

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [43]:
#(5). random module
#(a). randint()==> provide int number in agiven a range.
a= np.random.randint(1,20,4)
a

array([18, 19,  5,  4])

In [42]:
p=int(input("min. :"))
q=int(input("max. :"))
r=int(input("total :"))
a= np.random.randint(p,q,r)
a

min. : 1
max. : 50
total : 5


array([13, 20, 16, 33, 49])

In [44]:
#(b) rand()==>(0 to 1)
a=np.random.rand(5)
a

array([0.75230732, 0.11303489, 0.55258231, 0.03365855, 0.66819477])

In [45]:
a=np.random.rand(2,3)
a

array([[0.01510687, 0.31033243, 0.05635223],
       [0.12411939, 0.23990879, 0.13282263]])

In [46]:
#(c).randn()==>limit(-7 to 7)
a=np.random.randn(3)
a

array([-0.85059548, -2.37485258, -1.57904802])

In [47]:
a=np.random.randn(2,3)
a

array([[ 0.26683434, -0.23082786,  1.17980182],
       [ 0.08416606,  0.775681  , -1.17562055]])

In [49]:
#(6). seed()==> it will fix our numbers.
np.random.seed(56)
a=np.random.randint(1,10,3)
a

array([6, 5, 1])