In [1]:
#Reshaping the data

In [4]:
import numpy as np
a=np.random.randint(1,50,12)
a

array([ 4, 28, 38,  9, 22,  8, 14, 15, 10, 36, 48, 33])

In [5]:
a.reshape(2,6)

array([[ 4, 28, 38,  9, 22,  8],
       [14, 15, 10, 36, 48, 33]])

In [6]:
a.reshape(6,2)

array([[ 4, 28],
       [38,  9],
       [22,  8],
       [14, 15],
       [10, 36],
       [48, 33]])

In [7]:
a.reshape(3,4)

array([[ 4, 28, 38,  9],
       [22,  8, 14, 15],
       [10, 36, 48, 33]])

In [8]:
a.reshape(4,3)

array([[ 4, 28, 38],
       [ 9, 22,  8],
       [14, 15, 10],
       [36, 48, 33]])

In [9]:
a.reshape(5,4)#shows error because no. of elements is 12

ValueError: cannot reshape array of size 12 into shape (5,4)

In [10]:
b=np.random.randint(1,100,36)
b

array([31, 10, 66, 56, 39, 49, 83, 89, 40, 83, 19, 31, 81, 59, 20, 70, 87,
       26, 96, 42, 74, 19, 91,  5, 52, 89, 57, 52, 36, 94, 95, 90, 83, 21,
       80, 40])

In [11]:
b.reshape(2,18)

array([[31, 10, 66, 56, 39, 49, 83, 89, 40, 83, 19, 31, 81, 59, 20, 70,
        87, 26],
       [96, 42, 74, 19, 91,  5, 52, 89, 57, 52, 36, 94, 95, 90, 83, 21,
        80, 40]])

In [12]:
b.reshape(18,2)

array([[31, 10],
       [66, 56],
       [39, 49],
       [83, 89],
       [40, 83],
       [19, 31],
       [81, 59],
       [20, 70],
       [87, 26],
       [96, 42],
       [74, 19],
       [91,  5],
       [52, 89],
       [57, 52],
       [36, 94],
       [95, 90],
       [83, 21],
       [80, 40]])

In [13]:
b.reshape(3,12)

array([[31, 10, 66, 56, 39, 49, 83, 89, 40, 83, 19, 31],
       [81, 59, 20, 70, 87, 26, 96, 42, 74, 19, 91,  5],
       [52, 89, 57, 52, 36, 94, 95, 90, 83, 21, 80, 40]])

In [14]:
b.reshape(12,3)

array([[31, 10, 66],
       [56, 39, 49],
       [83, 89, 40],
       [83, 19, 31],
       [81, 59, 20],
       [70, 87, 26],
       [96, 42, 74],
       [19, 91,  5],
       [52, 89, 57],
       [52, 36, 94],
       [95, 90, 83],
       [21, 80, 40]])

In [15]:
b.reshape(4,9)

array([[31, 10, 66, 56, 39, 49, 83, 89, 40],
       [83, 19, 31, 81, 59, 20, 70, 87, 26],
       [96, 42, 74, 19, 91,  5, 52, 89, 57],
       [52, 36, 94, 95, 90, 83, 21, 80, 40]])

In [16]:
b.reshape(9,4)

array([[31, 10, 66, 56],
       [39, 49, 83, 89],
       [40, 83, 19, 31],
       [81, 59, 20, 70],
       [87, 26, 96, 42],
       [74, 19, 91,  5],
       [52, 89, 57, 52],
       [36, 94, 95, 90],
       [83, 21, 80, 40]])

In [19]:
#view vs copy
a=np.array([10,20,30,40,50,60,70,80])#view means mmodification in original data
b=a[3:6]
b[:]=0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [20]:
a=np.array([10,20,30,40,50,60,70,80])#copy means we make a duplicate entry and this 
b=a[3:6].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [24]:
a=np.arange(1,16)
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [25]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [27]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [28]:
#operations on array
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [29]:
a*2

array([2, 4, 6, 8])

In [30]:
a**2

array([ 1,  4,  9, 16])

In [31]:
a**3

array([ 1,  8, 27, 64], dtype=int32)

In [32]:
a=a.reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [34]:
b=np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [35]:
a+b

array([[ 6,  8],
       [10, 12]])

In [36]:
a-b

array([[-4, -4],
       [-4, -4]])

In [37]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [38]:
np.min(a)

1

In [39]:
np.argmin(a)#it gives min. value index

0

In [40]:
np.max(a)

4

In [41]:
np.argmax(a)

3

In [42]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [43]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [44]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [45]:
np.tan(a)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [47]:
#LinSpace==> this function returns value between a given range and with a same gap betwwen consecutive elemnts
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [48]:
#1.25-1=0.25
#1.50-1.25=0.25
#1.75-1.50=0.25
#2-1.75=0.25

In [49]:
np.random.seed(34)
a=np.random.randint(1,21,9).reshape(3,3)
a

array([[ 2, 11, 10],
       [ 5,  4,  6],
       [12, 11, 15]])

In [50]:
np.sum(a)

76

In [51]:
np.sum(a,axis=1)

array([23, 15, 38])

In [52]:
np.sum(a,axis=0)

array([19, 26, 31])

In [53]:
np.cumsum(a)

array([ 2, 13, 23, 28, 32, 38, 50, 61, 76])

In [ ]:
# np.unique(arr,return_index=True,return_counts=Ture)
#returns 3 array
#(1). the array with unique values
#(2). the array with respective index values
#(3). the array with counting of frequency

In [54]:
a=np.array([10,20,30,40,20,20,20,50,50])
np.unique(a,return_index=True,return_counts=True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 7], dtype=int64),
 array([1, 4, 1, 1, 2], dtype=int64))

In [56]:
# horizontal and vertical stackes
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [59]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])