# Encoding ==>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("C:\\Users\\user\\Datasets\\covid_toy.csv")

In [3]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df=df.drop(columns=['age','fever'],axis=1)

In [5]:
df.head()

gender cough     city has_covid
0    Male  Mild  Kolkata        No
1    Male  Mild    Delhi       Yes
2    Male  Mild    Delhi        No
3  Female  Mild  Kolkata        No
4  Female  Mild   Mumbai        No

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [7]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [8]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [9]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [10]:
oe=OrdinalEncoder(categories = [['Male','Female'],['Mild','Strong'],['Kolkata','Bangalore','Delhi','Mumbai'],['No','Yes']])

In [11]:
oe

OrdinalEncoder(categories=[['Male', 'Female'], ['Mild', 'Strong'],
                           ['Kolkata', 'Bangalore', 'Delhi', 'Mumbai'],
                           ['No', 'Yes']])

In [12]:
oe.fit(df)

OrdinalEncoder(categories=[['Male', 'Female'], ['Mild', 'Strong'],
                           ['Kolkata', 'Bangalore', 'Delhi', 'Mumbai'],
                           ['No', 'Yes']])

In [13]:
oe.transform(df)

array([[0., 0., 0., 0.],
       [0., 0., 2., 1.],
       [0., 0., 2., 0.],
       [1., 0., 0., 0.],
       [1., 0., 3., 0.],
       [1., 0., 1., 1.],
       [0., 1., 1., 0.],
       [1., 1., 3., 1.],
       [1., 1., 1., 0.],
       [1., 0., 2., 0.],
       [1., 0., 2., 0.],
       [1., 0., 3., 1.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 2., 0.],
       [1., 0., 1., 1.],
       [1., 1., 1., 1.],
       [0., 1., 1., 0.],
       [0., 0., 1., 1.],
       [1., 1., 0., 1.],
       [1., 0., 2., 1.],
       [1., 1., 0., 0.],
       [0., 0., 3., 0.],
       [1., 0., 0., 1.],
       [1., 1., 2., 0.],
       [0., 0., 0., 0.],
       [1., 1., 3., 1.],
       [0., 0., 2., 1.],
       [0., 0., 0., 0.],
       [1., 1., 2., 1.],
       [1., 0., 0., 0.],
       [0., 0., 3., 1.],
       [1., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 2., 1.],
       [1., 0., 0., 0.],


In [14]:
df=pd.read_csv("C:\\Users\\user\\Datasets\\tips.csv")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [15]:
df=df.drop(columns=['total_bill','tip','size'])

In [16]:
from sklearn.preprocessing import OrdinalEncoder

In [17]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [18]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [19]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [20]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [21]:
oe=OrdinalEncoder(categories=[['Male','Female'],['No','Yes'],['Sat','Sun','Thur','Fri'],['Dinner','Lunch']])

In [22]:
oe.fit(df)

OrdinalEncoder(categories=[['Male', 'Female'], ['No', 'Yes'],
                           ['Sat', 'Sun', 'Thur', 'Fri'], ['Dinner', 'Lunch']])

In [23]:
new_df=oe.transform(df)

In [24]:
new_df=pd.DataFrame(new_df,columns=df.columns)

In [25]:
new_df

sex  smoker  day  time
0    1.0     0.0  1.0   0.0
1    0.0     0.0  1.0   0.0
2    0.0     0.0  1.0   0.0
3    0.0     0.0  1.0   0.0
4    1.0     0.0  1.0   0.0
..   ...     ...  ...   ...
239  0.0     0.0  0.0   0.0
240  1.0     1.0  0.0   0.0
241  0.0     1.0  0.0   0.0
242  0.0     0.0  0.0   0.0
243  1.0     0.0  2.0   0.0

[244 rows x 4 columns]

In [26]:
x=new_df.drop(columns=['sex'],axis=1)
y=new_df['sex']

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42)

In [29]:
x_train

smoker  day  time
228     0.0  0.0   0.0
208     1.0  0.0   0.0
96      1.0  3.0   0.0
167     0.0  1.0   0.0
84      0.0  2.0   1.0
..      ...  ...   ...
106     1.0  0.0   0.0
14      0.0  1.0   0.0
92      1.0  3.0   0.0
179     1.0  1.0   0.0
102     1.0  0.0   0.0

[195 rows x 3 columns]

In [30]:
pd.get_dummies(new_df,columns=['sex','smoker','day','time'])

sex_0.0  sex_1.0  smoker_0.0  smoker_1.0  day_0.0  day_1.0  day_2.0  \
0      False     True        True       False    False     True    False   
1       True    False        True       False    False     True    False   
2       True    False        True       False    False     True    False   
3       True    False        True       False    False     True    False   
4      False     True        True       False    False     True    False   
..       ...      ...         ...         ...      ...      ...      ...   
239     True    False        True       False     True    False    False   
240    False     True       False        True     True    False    False   
241     True    False       False        True     True    False    False   
242     True    False        True       False     True    False    False   
243    False     True        True       False    False    False     True   

     day_3.0  time_0.0  time_1.0  
0      False      True     False  
1      False      True     False  
2      False      True     False  
3      False      True     False  
4      False      True     False  
..       ...       ...       ...  
239    False      True     False  
240    False      True     False  
241    False      True     False  
242    False      True     False  
243    False      True     False  

[244 rows x 10 columns]

In [31]:
pd.get_dummies(new_df,columns=['sex','smoker','day','time'],drop_first=True)

sex_1.0  smoker_1.0  day_1.0  day_2.0  day_3.0  time_1.0
0       True       False     True    False    False     False
1      False       False     True    False    False     False
2      False       False     True    False    False     False
3      False       False     True    False    False     False
4       True       False     True    False    False     False
..       ...         ...      ...      ...      ...       ...
239    False       False    False    False    False     False
240     True        True    False    False    False     False
241    False        True    False    False    False     False
242    False       False    False    False    False     False
243     True       False    False     True    False     False

[244 rows x 6 columns]

In [32]:
from sklearn.preprocessing import OneHotEncoder


In [36]:
oe=OneHotEncoder(drop='first',sparse=False)
df_new=oe.fit_transform(df[['sex','smoker','day','time']])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [37]:
df_new

array([[0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       ...,
       [1., 1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [38]:
df=pd.read_csv("C:\\Users\\user\\Datasets\\tips.csv")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [39]:
df=df.drop(columns=['total_bill','tip','size'])

In [40]:
oe=OneHotEncoder(drop='first',sparse=False)
df_new=oe.fit_transform(df[['sex','smoker','day','time']])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [41]:
df_new

array([[0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       ...,
       [1., 1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [42]:
from sklearn.preprocessing import LabelEncoder

In [43]:
lb=LabelEncoder()

In [44]:
df['sex']=lb.fit_transform(df['sex'])
df['smoker']=lb.fit_transform(df['smoker'])
df['day']=lb.fit_transform(df['day'])
df['time']=lb.fit_transform(df['time'])

In [46]:
df.head()

sex  smoker  day  time
0    0       0    2     0
1    1       0    2     0
2    1       0    2     0
3    1       0    2     0
4    0       0    2     0